### ISSUE TITLE
代码运行错误

### ISSUE THREAD

**Issue by zxfei1987** [Reallyhardtocreateaname/PhD-Thesis-Projects#1]
我正在拜读您于2022年发表在“INTERNATIONAL JOURNAL OF PRODUCTION RESEARCH”上的文章《Deep reinforcement learning for dynamic scheduling of a flexible job shop》，并下载了源代码。这些内容使我在研究FJSP的课题中受益匪浅，对我的研究提供了巨大的帮助。

同时，更深入的学习和运行FJSP代码的过程中，出现了一些错误。如下：

当运行Thesis_tournament_R.py时，出现了读取“IQL_5wc20m_0_globalR.pt”的错误，具体：
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\RL_Scheduling\\PhD-Thesis-Projects-main_improve\\FJSP\\routing_models\\independent\\IQL_5wc20m_0_globalR.pt'

请问这个错误该如何解决。

另外，routing models和 sequencing models文件夹中的.pt文件 是如何生成的？

非常期待得到您的指点和帮助。

再次感谢您的支持!

**Comment by Reallyhardtocreateaname** [comment]
你好，这里的代码是用于博士论文中的，与我发表的论文所使用的代码不尽相同。

运行 Thesis_tournament_R.py 所产生的错误，是没有找到相对应的神经网络参数。由于你选择了IQL (Independent Q-learning) 模式，此模式会为每一个智能体读取一套独立的网络参数，是我用于博士论文的 Ablation study 中的 worst case/ baseline performance。 由于不代表模型实际表现，所以并未上传。如有需要，可以在 Thesis_training_R 中选取IQL模式训练一套。

.pt文件在 Thesis_training_R 或 Thesis_training_S 训练完成后会自动生成。

谢谢支持。如有其他问题可联系我的邮箱 renke001@e.ntu.edu.sg

**Comment by zxfei1987** [comment]
太感谢了！我试试。
